# Alpha空投配置模板
# 请根据实际需求修改配置参数

# 空投任务配置
airdrop_tasks:
  - id: "airdrop_001"
    name: "Alpha代币空投活动1"
    description: "示例空投任务配置"
    enabled: true
    auto_claim: true
    config:
      max_retries: 3
      retry_delay: 2
      timeout: 30
      check_interval: 300  # 5分钟检查一次
    filters:
      min_reward_amount: 0.001  # 最小奖励金额
      supported_chains: ["BSC", "ETH", "POLYGON"]
      excluded_tokens: []
    notifications:
      webhook_url: ""
      enable_email: false
      email_recipients: []

  - id: "airdrop_002"
    name: "Alpha代币空投活动2" 
    description: "第二个空投任务示例"
    enabled: false
    auto_claim: false
    config:
      max_retries: 5
      retry_delay: 3
      timeout: 45
      check_interval: 600  # 10分钟检查一次
    filters:
      min_reward_amount: 0.01
      supported_chains: ["BSC"]
      excluded_tokens: ["SCAM_TOKEN"]
    notifications:
      webhook_url: "https://discord.com/api/webhooks/your_webhook_url"
      enable_email: true
      email_recipients: ["user@example.com"]

# 全局空投配置
global_config:
  # 并发设置
  max_concurrent_users: 5
  max_concurrent_tasks: 3
  
  # 请求配置
  default_timeout: 30
  default_retries: 3
  request_delay: 1  # 请求间隔（秒）
  
  # 代理配置
  use_proxy: false
  proxy_rotation: true
  proxy_file: "config/proxies.txt"
  
  # 日志配置
  log_level: "INFO"
  log_file: "logs/airdrop.log"
  enable_file_logging: true
  
  # 数据存储
  database_path: "data/airdrop_records.db"
  backup_interval: 3600  # 1小时备份一次
  
  # 安全配置
  rate_limit:
    requests_per_minute: 60
    requests_per_hour: 1000
  
  # 监控配置
  health_check:
    enabled: true
    interval: 300  # 5分钟检查一次
    webhook_url: ""

# 用户特定配置
user_configs:
  user1_pc:
    priority: 1
    enabled: true
    custom_delays:
      pre_claim_delay: 1
      post_claim_delay: 2
    reward_thresholds:
      min_claim_amount: 0.001
      max_daily_claims: 50
  
  user2_pc:
    priority: 2
    enabled: true
    custom_delays:
      pre_claim_delay: 2
      post_claim_delay: 3
    reward_thresholds:
      min_claim_amount: 0.005
      max_daily_claims: 30

# 通知配置
notifications:
  # Discord Webhook
  discord:
    enabled: false
    webhook_url: ""
    mention_role: ""
    
  # 邮件通知
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    from_email: ""
    
  # 微信通知（企业微信）
  wechat:
    enabled: false
    webhook_url: ""
    
  # Telegram通知
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""

# 风险控制
risk_control:
  # 交易限制
  daily_limits:
    max_transactions: 100
    max_volume: 1000
    max_gas_fee: 0.1
  
  # 异常检测
  anomaly_detection:
    enabled: true
    min_success_rate: 0.8
    max_error_rate: 0.2
    alert_threshold: 10
  
  # 黑名单
  blacklist:
    contracts: []
    tokens: []
    addresses: [] 